export const FETCH_INFLUENCERS = 'FETCH_INFLUENCERS';
export const ADD_SELECTED_INFLUENCER = 'ADD_SELECTED_INFLUENCER';
export const REMOVE_SELECTED_INFLUENCER = 'REMOVE_SELECTED_INFLUENCER';
export const REMOVE_ALL_SELECTED_INFLUENCER = 'REMOVE_ALL_SELECTED_INFLUENCER';
export const DELETE_SELECTED_INFLUENCER = 'DELETE_SELECTED_INFLUENCER';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const FETCH_PLATFORMS = 'FETCH_PLATFORMS';
